"""Standalone submission for Kaggle Kaggriculture simulation.
Generated by Kaggriculture Autonomous Framework.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        inv = inventories[0] if inventories else {}

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce
        for item, qty in shed.items():
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # 2. Market Phase: Smart Seed Buying
        m_seeds = seeds.get("MELON", 0)
        c_seeds = seeds.get("CARROT", 0)
        money = farm.get("money", 0)

        want_melons = (day <= 2 or 12 <= day <= 14) and m_seeds < 2
        if want_melons and money >= 80:
            needed_melons = min(2 - m_seeds, int(money // 80))
            if needed_melons > 0:
                market_orders.append(["BUY_SEED", "MELON", needed_melons])

        if day <= 26 and c_seeds < 3 and money >= 20:
            needed_carrots = min(3 - c_seeds, int(money // 20))
            if needed_carrots > 0:
                market_orders.append(["BUY_SEED", "CARROT", needed_carrots])

        market_orders = market_orders[:10]
        cluster = [(4, 4), (3, 4), (4, 3), (3, 3)]
        melon_slots = [(3, 4), (4, 3)]
        shed_access = (4, 4)
        carrying_items = any(qty > 0 for qty in inv.values())

        # 3. Shed Drop
        if (fx, fy) == shed_access and carrying_items:
            return {"farmer": ["DROP"], "hands": [], "market": market_orders}

        # 4. Immediate Work on Current Tile
        if fy < len(tiles) and fx < len(tiles[0]):
            t = tiles[fy][fx]
            if isinstance(t, dict):
                kind = t.get("kind")
                if kind == "PLANT":
                    crop = t.get("crop", "CARROT")
                    age = day - t.get("planted_day", 0)
                    yield_units = t.get("yield_units", 0)
                    max_age = 12 if crop == "MELON" else 3
                    if age >= max_age and yield_units > 0:
                        return {"farmer": ["HARVEST"], "hands": [], "market": market_orders}
                    elif not t.get("watered_today", False) and day <= 28:
                        return {"farmer": ["WATER"], "hands": [], "market": market_orders}
                elif kind == "WEED":
                    return {"farmer": ["DIG"], "hands": [], "market": market_orders}
            elif t is None and (fx, fy) in cluster:
                if (fx, fy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                    return {"farmer": ["PLANT", "MELON"], "hands": [], "market": market_orders}
                elif c_seeds > 0 and day <= 26:
                    return {"farmer": ["PLANT", "CARROT"], "hands": [], "market": market_orders}

        # 5. Cluster Work Scheduling
        needed_tasks = []
        for cx, cy in cluster:
            if cy >= len(tiles) or cx >= len(tiles[0]):
                continue
            ct = tiles[cy][cx]
            if isinstance(ct, dict):
                k = ct.get("kind")
                if k == "PLANT":
                    crop = ct.get("crop", "CARROT")
                    age = day - ct.get("planted_day", 0)
                    yield_units = ct.get("yield_units", 0)
                    max_age = 12 if crop == "MELON" else 3
                    if age >= max_age and yield_units > 0:
                        needed_tasks.append(((cx, cy), 1))
                    elif not ct.get("watered_today", False) and day <= 28:
                        needed_tasks.append(((cx, cy), 2))
                elif k == "WEED":
                    needed_tasks.append(((cx, cy), 3))
            elif ct is None and day <= 26:
                if (cx, cy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                    needed_tasks.append(((cx, cy), 4))
                elif c_seeds > 0:
                    needed_tasks.append(((cx, cy), 4))

        # 6. Navigation
        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        if needed_tasks:
            needed_tasks.sort(key=lambda item: (item[1], abs(fx - item[0][0]) + abs(fy - item[0][1])))
            tx, ty = needed_tasks[0][0]
            step = _step_direction((fx, fy), (tx, ty))
            return {"farmer": [step], "hands": [], "market": market_orders}
        elif carrying_items:
            tx, ty = shed_access
            step = _step_direction((fx, fy), (tx, ty))
            return {"farmer": [step], "hands": [], "market": market_orders}

        return {"farmer": ["PASS"], "hands": [], "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
