"""Builds and verifies a standalone, zero-dependency submission.py for Kaggle."""

from __future__ import annotations
import argparse
from pathlib import Path
import sys
import kaggle_environments as ke

ROOT = Path(__file__).resolve().parent.parent

SUBMISSION_TEMPLATE = '''"""Standalone submission for Kaggle Kaggriculture simulation.
Generated by Kaggriculture Autonomous Framework.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        inv = inventories[0] if inventories else {}

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce
        for item, qty in shed.items():
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # 2. Market Phase: Keep Carrot Seeds Stocked (Target: 4 seeds)
        carrot_seeds = seeds.get("CARROT", 0)
        seed_cost = 20
        if day <= 26 and carrot_seeds < 4 and farm.get("money", 0) >= seed_cost:
            needed = min(4 - carrot_seeds, int(farm["money"] // seed_cost))
            if needed > 0:
                market_orders.append(["BUY_SEED", "CARROT", needed])

        market_orders = market_orders[:10]
        cluster = [(4, 4), (3, 4), (4, 3), (3, 3)]
        shed_access = (4, 4)
        carrying_items = any(qty > 0 for qty in inv.values())

        # 3. Shed Drop
        if (fx, fy) == shed_access and carrying_items:
            return {"farmer": ["DROP"], "hands": [], "market": market_orders}

        # 4. Immediate Work on Current Tile
        if fy < len(tiles) and fx < len(tiles[0]):
            t = tiles[fy][fx]
            if isinstance(t, dict):
                kind = t.get("kind")
                if kind == "PLANT":
                    crop = t.get("crop", "CARROT")
                    age = day - t.get("planted_day", 0)
                    yield_units = t.get("yield_units", 0)
                    if age >= 3 and yield_units > 0:
                        return {"farmer": ["HARVEST"], "hands": [], "market": market_orders}
                    elif not t.get("watered_today", False) and day <= 28:
                        return {"farmer": ["WATER"], "hands": [], "market": market_orders}
                elif kind == "WEED":
                    return {"farmer": ["DIG"], "hands": [], "market": market_orders}
            elif t is None and carrot_seeds > 0 and day <= 26 and (fx, fy) in cluster:
                return {"farmer": ["PLANT", "CARROT"], "hands": [], "market": market_orders}

        # 5. Cluster Work Scheduling
        needed_tasks = []
        for cx, cy in cluster:
            if cy >= len(tiles) or cx >= len(tiles[0]):
                continue
            ct = tiles[cy][cx]
            if isinstance(ct, dict):
                k = ct.get("kind")
                if k == "PLANT":
                    age = day - ct.get("planted_day", 0)
                    yield_units = ct.get("yield_units", 0)
                    if age >= 3 and yield_units > 0:
                        needed_tasks.append(((cx, cy), 1))
                    elif not ct.get("watered_today", False) and day <= 28:
                        needed_tasks.append(((cx, cy), 2))
                elif k == "WEED":
                    needed_tasks.append(((cx, cy), 3))
            elif ct is None and carrot_seeds > 0 and day <= 26:
                needed_tasks.append(((cx, cy), 4))

        # 6. Navigation
        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        if needed_tasks:
            needed_tasks.sort(key=lambda item: (item[1], abs(fx - item[0][0]) + abs(fy - item[0][1])))
            tx, ty = needed_tasks[0][0]
            step = _step_direction((fx, fy), (tx, ty))
            return {"farmer": [step], "hands": [], "market": market_orders}
        elif carrying_items:
            tx, ty = shed_access
            step = _step_direction((fx, fy), (tx, ty))
            return {"farmer": [step], "hands": [], "market": market_orders}

        return {"farmer": ["PASS"], "hands": [], "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def build_submission(target_path: Path = ROOT / "submission.py", verify: bool = True) -> bool:
    print(f"Generating submission file at: {target_path}")
    target_path.write_text(SUBMISSION_TEMPLATE, encoding="utf-8")

    if not verify:
        print("[SUCCESS] submission.py written without verification.")
        return True

    print("Verifying submission.py against kaggle-environments...")
    env = ke.make("kaggriculture", debug=True)
    env.run([str(target_path), "starter"])

    reward_sub = env.steps[-1][0]["reward"]
    reward_opp = env.steps[-1][1]["reward"]
    status_sub = env.steps[-1][0]["status"]
    status_opp = env.steps[-1][1]["status"]

    print(f"Verification Results:")
    print(f"  Total Steps: {len(env.steps)}")
    print(f"  Submission Status: {status_sub}, Reward: ${reward_sub:,.2f}")
    print(f"  Opponent Status:   {status_opp}, Reward: ${reward_opp:,.2f}")

    if status_sub != "DONE" or reward_sub is None or reward_sub <= 0:
        print(f"[FAIL] Submission verification failed! Status: {status_sub}")
        return False

    print("[SUCCESS] submission.py verified successfully and ready for upload!")
    return True


def main():
    parser = argparse.ArgumentParser(description="Build and verify Kaggriculture submission.py")
    parser.add_argument("--verify", action="store_true", default=True, help="Verify submission with a test game")
    parser.add_argument("--output", type=str, default="submission.py", help="Output file path")
    args = parser.parse_args()

    success = build_submission(target_path=ROOT / args.output, verify=args.verify)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
