"""Builds and verifies a standalone, zero-dependency submission.py for Kaggle."""

from __future__ import annotations
import argparse
from pathlib import Path
import sys
import kaggle_environments as ke

ROOT = Path(__file__).resolve().parent.parent

SUBMISSION_TEMPLATE = '''"""Standalone submission for Kaggle Kaggriculture simulation (FarmBrain v3.0).
Generated by Kaggriculture Autonomous Framework.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        hands_pos = farm.get("hands", [])
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        f_inv = inventories[0] if inventories else {}
        money = farm.get("money", 0)

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce
        for item, qty in shed.items():
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # 2. Market Phase: Labor Scaling (Hire up to 2 hands per day)
        if day <= 25 and len(hands_pos) < 2 and money >= 25:
            market_orders.append(["HIRE"])

        # 3. Market Phase: Mega Seed Purchasing
        m_seeds = seeds.get("MELON", 0)
        c_seeds = seeds.get("CARROT", 0)

        # Melon batches: Batch 1 (Days 0-2), Batch 2 (Days 12-14)
        want_melons = (day <= 2 or 12 <= day <= 14) and m_seeds < 14
        if want_melons and money >= 80:
            needed_melons = min(14 - m_seeds, int(money // 80))
            if needed_melons > 0:
                market_orders.append(["BUY_SEED", "MELON", needed_melons])

        if day <= 26 and c_seeds < 4 and money >= 20:
            needed_carrots = min(4 - c_seeds, int(money // 20))
            if needed_carrots > 0:
                market_orders.append(["BUY_SEED", "CARROT", needed_carrots])

        market_orders = market_orders[:10]

        shed_access = (4, 4)
        # 14 high-density melon slots surrounding shed access (4,4)
        melon_slots = [
            (3, 4), (4, 3), (3, 3), (2, 4), (4, 2), (2, 3), (3, 2), (2, 2),
            (1, 4), (4, 1), (1, 3), (3, 1), (1, 2), (2, 1)
        ]
        # 14 melon slots + 4 carrot slots + shed tile (19 tiles total in Quadrant 0)
        cluster = [
            (4, 4),
            (3, 4), (4, 3), (3, 3), (2, 4), (4, 2), (2, 3), (3, 2), (2, 2),
            (1, 4), (4, 1), (1, 3), (3, 1), (1, 2), (2, 1),
            (0, 4), (4, 0), (0, 3), (3, 0)
        ]

        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        claimed_targets = set()

        def resolve_worker_action(wx, wy, worker_inv):
            has_items = any(qty > 0 for qty in worker_inv.values())

            # Shed drop
            if (wx, wy) == shed_access and has_items:
                return ["DROP"]

            # Current tile work
            if wy < len(tiles) and wx < len(tiles[0]):
                ct = tiles[wy][wx]
                if isinstance(ct, dict):
                    k = ct.get("kind")
                    if k == "PLANT":
                        crop = ct.get("crop")
                        age = day - ct.get("planted_day", 0)
                        y_units = ct.get("yield_units", 0)
                        max_age = 12 if crop == "MELON" else 3
                        if age >= max_age and y_units > 0:
                            claimed_targets.add((wx, wy))
                            return ["HARVEST"]
                        elif not ct.get("watered_today", False) and day <= 28:
                            claimed_targets.add((wx, wy))
                            return ["WATER"]
                    elif k == "WEED":
                        claimed_targets.add((wx, wy))
                        return ["DIG"]
                elif ct is None and (wx, wy) in cluster:
                    if (wx, wy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "MELON"]
                    elif c_seeds > 0 and day <= 26:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "CARROT"]

            # Find nearest unclaimed cluster tile needing attention
            needed = []
            for cx, cy in cluster:
                if (cx, cy) in claimed_targets:
                    continue
                if cy >= len(tiles) or cx >= len(tiles[0]):
                    continue
                t = tiles[cy][cx]
                if isinstance(t, dict):
                    k = t.get("kind")
                    if k == "PLANT":
                        crop = t.get("crop")
                        age = day - t.get("planted_day", 0)
                        y_units = t.get("yield_units", 0)
                        max_age = 12 if crop == "MELON" else 3
                        if age >= max_age and y_units > 0:
                            needed.append(((cx, cy), 1))
                        elif not t.get("watered_today", False) and day <= 28:
                            needed.append(((cx, cy), 2))
                    elif k == "WEED":
                        needed.append(((cx, cy), 3))
                elif t is None and day <= 26:
                    if (cx, cy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        needed.append(((cx, cy), 4))
                    elif c_seeds > 0:
                        needed.append(((cx, cy), 4))

            if needed:
                needed.sort(key=lambda item: (item[1], abs(wx - item[0][0]) + abs(wy - item[0][1])))
                tx, ty = needed[0][0]
                claimed_targets.add((tx, ty))
                return [_step_direction((wx, wy), (tx, ty))]
            elif has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            return ["PASS"]

        farmer_act = resolve_worker_action(fx, fy, f_inv)

        hands_act = []
        for h_idx, (hx, hy) in enumerate(hands_pos):
            h_inv = inventories[h_idx + 1] if len(inventories) > h_idx + 1 else {}
            h_act = resolve_worker_action(hx, hy, h_inv)
            hands_act.append(h_act)

        return {"farmer": farmer_act, "hands": hands_act, "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def build_submission(target_path: Path = ROOT / "submission.py", verify: bool = True) -> bool:
    print(f"Generating submission file at: {target_path}")
    target_path.write_text(SUBMISSION_TEMPLATE, encoding="utf-8")

    if not verify:
        print("[SUCCESS] submission.py written without verification.")
        return True

    print("Verifying submission.py against kaggle-environments...")
    env = ke.make("kaggriculture", debug=True)
    env.run([str(target_path), "starter"])

    reward_sub = env.steps[-1][0]["reward"]
    reward_opp = env.steps[-1][1]["reward"]
    status_sub = env.steps[-1][0]["status"]
    status_opp = env.steps[-1][1]["status"]

    print(f"Verification Results:")
    print(f"  Total Steps: {len(env.steps)}")
    print(f"  Submission Status: {status_sub}, Reward: ${reward_sub:,.2f}")
    print(f"  Opponent Status:   {status_opp}, Reward: ${reward_opp:,.2f}")

    if status_sub != "DONE" or reward_sub is None or reward_sub <= 0:
        print(f"[FAIL] Submission verification failed! Status: {status_sub}")
        return False

    print("[SUCCESS] submission.py verified successfully and ready for upload!")
    return True


def main():
    parser = argparse.ArgumentParser(description="Build and verify Kaggriculture submission.py")
    parser.add_argument("--verify", action="store_true", default=True, help="Verify submission with a test game")
    parser.add_argument("--output", type=str, default="submission.py", help="Output file path")
    args = parser.parse_args()

    success = build_submission(target_path=ROOT / args.output, verify=args.verify)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
