"""Generates and verifies today's 5 Kaggle submissions (#6 to #10)."""

from pathlib import Path
import kaggle_environments as ke

# Template for v8: Quad-Labor Industrial (12M + 4S + 4C + 3 Hands)
V8_CODE = '''"""Standalone submission for Kaggle Kaggriculture simulation (FarmBrain v8.0 Quad-Labor).
Generated by Kaggriculture Autonomous Framework.
Strategy: Quad-Labor Industrial Engine (12 Melons + 4 Strawberries + 4 Carrots + 3 Farmhands).
High throughput (96 worker actions/day), high town shop strawberry absorption, complete immunity to melon crash.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        hands_pos = farm.get("hands", [])
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        f_inv = inventories[0] if inventories else {}
        money = farm.get("money", 0)

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce by Value Priority
        for item in ["MELON", "STRAWBERRY", "TOMATO", "CARROT", "WHEAT"]:
            qty = shed.get(item, 0)
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # 2. Labor Scaling: 3 Farmhands (96 actions/day across 4 workers)
        if day <= 25 and len(hands_pos) < 3 and money >= 25:
            market_orders.append(["HIRE"])

        # 3. Seed Purchasing: 4 Strawberries, 12 Melons, 4 Carrots
        s_seeds = seeds.get("STRAWBERRY", 0)
        m_seeds = seeds.get("MELON", 0)
        c_seeds = seeds.get("CARROT", 0)

        if day <= 2 and s_seeds < 4 and money >= 100:
            ns = min(4 - s_seeds, int(money // 100))
            if ns > 0:
                market_orders.append(["BUY_SEED", "STRAWBERRY", ns])

        want_melons = (day <= 2 or 12 <= day <= 14) and m_seeds < 12
        if want_melons and money >= 80:
            nm = min(12 - m_seeds, int(money // 80))
            if nm > 0:
                market_orders.append(["BUY_SEED", "MELON", nm])

        if day <= 26 and c_seeds < 4 and money >= 20:
            nc = min(4 - c_seeds, int(money // 20))
            if nc > 0:
                market_orders.append(["BUY_SEED", "CARROT", nc])

        market_orders = market_orders[:10]

        shed_access = (4, 4)

        # High-density slots in Quadrant 0 (NW)
        # 4 Strawberries closest to shed
        strawberry_slots = [(3, 4), (4, 3), (3, 3), (2, 4)]
        # 12 Melons surrounding strawberries
        melon_slots = [
            (4, 2), (2, 3), (3, 2), (2, 2), (1, 4), (4, 1),
            (1, 3), (3, 1), (1, 2), (2, 1), (0, 4), (4, 0)
        ]
        # 4 Carrots
        carrot_slots = [(0, 3), (3, 0), (0, 2), (2, 0)]

        cluster = [shed_access] + strawberry_slots + melon_slots + carrot_slots

        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        claimed_targets = set()

        def resolve_worker_action(wx, wy, worker_inv):
            has_items = any(qty > 0 for qty in worker_inv.values())

            # Shed drop priority
            if (wx, wy) == shed_access and has_items:
                return ["DROP"]

            # Current tile work
            if wy < len(tiles) and wx < len(tiles[0]):
                ct = tiles[wy][wx]
                if isinstance(ct, dict):
                    k = ct.get("kind")
                    if k == "PLANT":
                        crop = ct.get("crop")
                        age = day - ct.get("planted_day", 0)
                        y_units = ct.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            claimed_targets.add((wx, wy))
                            return ["HARVEST"]
                        elif not ct.get("watered_today", False) and day <= 28:
                            claimed_targets.add((wx, wy))
                            return ["WATER"]
                    elif k == "WEED":
                        claimed_targets.add((wx, wy))
                        return ["DIG"]
                elif ct is None and (wx, wy) in cluster:
                    if (wx, wy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "STRAWBERRY"]
                    elif (wx, wy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "MELON"]
                    elif (wx, wy) in carrot_slots and c_seeds > 0 and day <= 26:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "CARROT"]

            # Find nearest unclaimed cluster tile needing attention
            needed = []
            for cx, cy in cluster:
                if (cx, cy) in claimed_targets:
                    continue
                if cy >= len(tiles) or cx >= len(tiles[0]):
                    continue
                t = tiles[cy][cx]
                if isinstance(t, dict):
                    k = t.get("kind")
                    if k == "PLANT":
                        crop = t.get("crop")
                        age = day - t.get("planted_day", 0)
                        y_units = t.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            needed.append(((cx, cy), 1))
                        elif not t.get("watered_today", False) and day <= 28:
                            needed.append(((cx, cy), 2))
                    elif k == "WEED":
                        needed.append(((cx, cy), 3))
                elif t is None and day <= 26:
                    if (cx, cy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in carrot_slots and c_seeds > 0:
                        needed.append(((cx, cy), 4))

            # Day 29 Emergency Evacuation: drop all backpack items to maximize final money
            if day >= 29 and has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            if needed:
                needed.sort(key=lambda item: (item[1], abs(wx - item[0][0]) + abs(wy - item[0][1])))
                tx, ty = needed[0][0]
                claimed_targets.add((tx, ty))
                return [_step_direction((wx, wy), (tx, ty))]
            elif has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            return ["PASS"]

        farmer_act = resolve_worker_action(fx, fy, f_inv)

        hands_act = []
        for h_idx, (hx, hy) in enumerate(hands_pos):
            h_inv = inventories[h_idx + 1] if len(inventories) > h_idx + 1 else {}
            h_act = resolve_worker_action(hx, hy, h_inv)
            hands_act.append(h_act)

        return {"farmer": farmer_act, "hands": hands_act, "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''

# Template for v9: Adaptive Quad-Labor
V9_CODE = '''"""Standalone submission for Kaggle Kaggriculture simulation (FarmBrain v9.0 Adaptive Quad).
Generated by Kaggriculture Autonomous Framework.
Strategy: Dynamic Opponent Profiler + Quad-Labor Engine.
If opponent rushes melons (>=4), deploys 12 Melons + 4 Strawberries + 4 Carrots + 3 Hands to crush opponent.
If opponent is passive (<4), deploys 16 Melons + 4 Carrots + 3 Hands to capture maximum monopoly profit.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        opp_player = 1 - player
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        hands_pos = farm.get("hands", [])
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        f_inv = inventories[0] if inventories else {}
        money = farm.get("money", 0)

        # Opponent Profiling
        opp_farm = farms[opp_player] if len(farms) > opp_player else {}
        opp_tiles = opp_farm.get("tiles", [])
        opp_melons = 0
        for row in opp_tiles:
            for t in row:
                if isinstance(t, dict) and t.get("crop") == "MELON":
                    opp_melons += 1

        if opp_melons >= 4:
            num_melons = 12
            num_strawberries = 4
            num_carrots = 4
        else:
            num_melons = 16
            num_strawberries = 0
            num_carrots = 4

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce
        for item in ["MELON", "STRAWBERRY", "TOMATO", "CARROT", "WHEAT"]:
            qty = shed.get(item, 0)
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # 2. Labor Scaling: 3 Farmhands
        if day <= 25 and len(hands_pos) < 3 and money >= 25:
            market_orders.append(["HIRE"])

        # 3. Seed Purchasing
        s_seeds = seeds.get("STRAWBERRY", 0)
        m_seeds = seeds.get("MELON", 0)
        c_seeds = seeds.get("CARROT", 0)

        if num_strawberries > 0 and day <= 2 and s_seeds < num_strawberries and money >= 100:
            ns = min(num_strawberries - s_seeds, int(money // 100))
            if ns > 0:
                market_orders.append(["BUY_SEED", "STRAWBERRY", ns])

        want_melons = (day <= 2 or 12 <= day <= 14) and m_seeds < num_melons
        if want_melons and money >= 80:
            nm = min(num_melons - m_seeds, int(money // 80))
            if nm > 0:
                market_orders.append(["BUY_SEED", "MELON", nm])

        if day <= 26 and c_seeds < num_carrots and money >= 20:
            nc = min(num_carrots - c_seeds, int(money // 20))
            if nc > 0:
                market_orders.append(["BUY_SEED", "CARROT", nc])

        market_orders = market_orders[:10]

        shed_access = (4, 4)
        candidates = [
            (3, 4), (4, 3), (3, 3), (2, 4), (4, 2), (2, 3), (3, 2), (2, 2),
            (1, 4), (4, 1), (1, 3), (3, 1), (1, 2), (2, 1), (0, 4), (4, 0),
            (0, 3), (3, 0), (0, 2), (2, 0), (0, 1), (1, 0), (1, 1), (0, 0)
        ]

        strawberry_slots = candidates[:num_strawberries]
        melon_slots = candidates[num_strawberries : num_strawberries + num_melons]
        carrot_slots = candidates[num_strawberries + num_melons : num_strawberries + num_melons + num_carrots]

        cluster = [shed_access] + strawberry_slots + melon_slots + carrot_slots

        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        claimed_targets = set()

        def resolve_worker_action(wx, wy, worker_inv):
            has_items = any(qty > 0 for qty in worker_inv.values())

            if (wx, wy) == shed_access and has_items:
                return ["DROP"]

            if wy < len(tiles) and wx < len(tiles[0]):
                ct = tiles[wy][wx]
                if isinstance(ct, dict):
                    k = ct.get("kind")
                    if k == "PLANT":
                        crop = ct.get("crop")
                        age = day - ct.get("planted_day", 0)
                        y_units = ct.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            claimed_targets.add((wx, wy))
                            return ["HARVEST"]
                        elif not ct.get("watered_today", False) and day <= 28:
                            claimed_targets.add((wx, wy))
                            return ["WATER"]
                    elif k == "WEED":
                        claimed_targets.add((wx, wy))
                        return ["DIG"]
                elif ct is None and (wx, wy) in cluster:
                    if (wx, wy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "STRAWBERRY"]
                    elif (wx, wy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "MELON"]
                    elif (wx, wy) in carrot_slots and c_seeds > 0 and day <= 26:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "CARROT"]

            needed = []
            for cx, cy in cluster:
                if (cx, cy) in claimed_targets:
                    continue
                if cy >= len(tiles) or cx >= len(tiles[0]):
                    continue
                t = tiles[cy][cx]
                if isinstance(t, dict):
                    k = t.get("kind")
                    if k == "PLANT":
                        crop = t.get("crop")
                        age = day - t.get("planted_day", 0)
                        y_units = t.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            needed.append(((cx, cy), 1))
                        elif not t.get("watered_today", False) and day <= 28:
                            needed.append(((cx, cy), 2))
                    elif k == "WEED":
                        needed.append(((cx, cy), 3))
                elif t is None and day <= 26:
                    if (cx, cy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in carrot_slots and c_seeds > 0:
                        needed.append(((cx, cy), 4))

            if day >= 29 and has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            if needed:
                needed.sort(key=lambda item: (item[1], abs(wx - item[0][0]) + abs(wy - item[0][1])))
                tx, ty = needed[0][0]
                claimed_targets.add((tx, ty))
                return [_step_direction((wx, wy), (tx, ty))]
            elif has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            return ["PASS"]

        farmer_act = resolve_worker_action(fx, fy, f_inv)

        hands_act = []
        for h_idx, (hx, hy) in enumerate(hands_pos):
            h_inv = inventories[h_idx + 1] if len(inventories) > h_idx + 1 else {}
            h_act = resolve_worker_action(hx, hy, h_inv)
            hands_act.append(h_act)

        return {"farmer": farmer_act, "hands": hands_act, "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''

# Template for v10: Apex Market Arbitrageur
V10_CODE = '''"""Standalone submission for Kaggle Kaggriculture simulation (FarmBrain v10.0 Apex Arbitrageur).
Generated by Kaggriculture Autonomous Framework.
Strategy: Quad-Labor Engine + Adaptive Opponent Profiler + Intelligent Market Anti-Dumping.
Staggers melon sales to preserve price above catastrophic floor, maximizes Strawberry/Carrot town absorption,
and executes emergency shed dump on Day 29.
"""

def agent(obs, config=None):
    try:
        farms = obs.get("farms", [])
        player = obs.get("player", 0)
        opp_player = 1 - player
        private = obs.get("private", {}) or {}
        if not farms or player >= len(farms):
            return {"farmer": ["PASS"], "hands": [], "market": []}

        farm = farms[player]
        fx, fy = farm.get("farmer", (4, 4))
        hands_pos = farm.get("hands", [])
        tiles = farm.get("tiles", [])
        day = obs.get("day", 0)
        seeds = private.get("seeds", {})
        shed = private.get("shed", {})
        inventories = private.get("inventories", [])
        f_inv = inventories[0] if inventories else {}
        money = farm.get("money", 0)
        market_obs = obs.get("market", {}) or {}
        market_prices = market_obs.get("prices", {})

        # Opponent Profiling
        opp_farm = farms[opp_player] if len(farms) > opp_player else {}
        opp_tiles = opp_farm.get("tiles", [])
        opp_melons = 0
        for row in opp_tiles:
            for t in row:
                if isinstance(t, dict) and t.get("crop") == "MELON":
                    opp_melons += 1

        if opp_melons >= 4:
            num_melons = 12
            num_strawberries = 4
            num_carrots = 4
        else:
            num_melons = 16
            num_strawberries = 0
            num_carrots = 4

        market_orders = []

        # 1. Market Phase: Liquidate Shed Produce with Anti-Dumping Stagger
        # Always liquidate strawberries and carrots immediately (high town absorption)
        for item in ["STRAWBERRY", "CARROT", "TOMATO", "WHEAT"]:
            qty = shed.get(item, 0)
            if qty > 0:
                market_orders.append(["SELL", item, qty])

        # Melons: Sell smoothly to avoid instant price collapse. On Day 29, dump everything.
        m_qty = shed.get("MELON", 0)
        if m_qty > 0:
            if day >= 29:
                market_orders.append(["SELL", "MELON", m_qty])
            else:
                # Sell in batches of at most 10 per turn to ride price elasticity
                sell_batch = min(m_qty, 10)
                market_orders.append(["SELL", "MELON", sell_batch])

        # 2. Labor Scaling: 3 Farmhands
        if day <= 25 and len(hands_pos) < 3 and money >= 25:
            market_orders.append(["HIRE"])

        # 3. Seed Purchasing
        s_seeds = seeds.get("STRAWBERRY", 0)
        m_seeds = seeds.get("MELON", 0)
        c_seeds = seeds.get("CARROT", 0)

        if num_strawberries > 0 and day <= 2 and s_seeds < num_strawberries and money >= 100:
            ns = min(num_strawberries - s_seeds, int(money // 100))
            if ns > 0:
                market_orders.append(["BUY_SEED", "STRAWBERRY", ns])

        want_melons = (day <= 2 or 12 <= day <= 14) and m_seeds < num_melons
        if want_melons and money >= 80:
            nm = min(num_melons - m_seeds, int(money // 80))
            if nm > 0:
                market_orders.append(["BUY_SEED", "MELON", nm])

        if day <= 26 and c_seeds < num_carrots and money >= 20:
            nc = min(num_carrots - c_seeds, int(money // 20))
            if nc > 0:
                market_orders.append(["BUY_SEED", "CARROT", nc])

        market_orders = market_orders[:10]

        shed_access = (4, 4)
        candidates = [
            (3, 4), (4, 3), (3, 3), (2, 4), (4, 2), (2, 3), (3, 2), (2, 2),
            (1, 4), (4, 1), (1, 3), (3, 1), (1, 2), (2, 1), (0, 4), (4, 0),
            (0, 3), (3, 0), (0, 2), (2, 0), (0, 1), (1, 0), (1, 1), (0, 0)
        ]

        strawberry_slots = candidates[:num_strawberries]
        melon_slots = candidates[num_strawberries : num_strawberries + num_melons]
        carrot_slots = candidates[num_strawberries + num_melons : num_strawberries + num_melons + num_carrots]

        cluster = [shed_access] + strawberry_slots + melon_slots + carrot_slots

        def _step_direction(current, target):
            cx, cy = current
            tx, ty = target
            if cx < tx:
                return "EAST"
            elif cx > tx:
                return "WEST"
            elif cy < ty:
                return "SOUTH"
            elif cy > ty:
                return "NORTH"
            return "PASS"

        claimed_targets = set()

        def resolve_worker_action(wx, wy, worker_inv):
            has_items = any(qty > 0 for qty in worker_inv.values())

            if (wx, wy) == shed_access and has_items:
                return ["DROP"]

            if wy < len(tiles) and wx < len(tiles[0]):
                ct = tiles[wy][wx]
                if isinstance(ct, dict):
                    k = ct.get("kind")
                    if k == "PLANT":
                        crop = ct.get("crop")
                        age = day - ct.get("planted_day", 0)
                        y_units = ct.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            claimed_targets.add((wx, wy))
                            return ["HARVEST"]
                        elif not ct.get("watered_today", False) and day <= 28:
                            claimed_targets.add((wx, wy))
                            return ["WATER"]
                    elif k == "WEED":
                        claimed_targets.add((wx, wy))
                        return ["DIG"]
                elif ct is None and (wx, wy) in cluster:
                    if (wx, wy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "STRAWBERRY"]
                    elif (wx, wy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "MELON"]
                    elif (wx, wy) in carrot_slots and c_seeds > 0 and day <= 26:
                        claimed_targets.add((wx, wy))
                        return ["PLANT", "CARROT"]

            needed = []
            for cx, cy in cluster:
                if (cx, cy) in claimed_targets:
                    continue
                if cy >= len(tiles) or cx >= len(tiles[0]):
                    continue
                t = tiles[cy][cx]
                if isinstance(t, dict):
                    k = t.get("kind")
                    if k == "PLANT":
                        crop = t.get("crop")
                        age = day - t.get("planted_day", 0)
                        y_units = t.get("yield_units", 0)
                        if crop == "MELON":
                            mature = (age >= 12 and y_units > 0)
                        elif crop == "STRAWBERRY":
                            mature = (age >= 10 and y_units > 0)
                        else:
                            mature = (age >= 3 and y_units > 0)

                        if mature:
                            needed.append(((cx, cy), 1))
                        elif not t.get("watered_today", False) and day <= 28:
                            needed.append(((cx, cy), 2))
                    elif k == "WEED":
                        needed.append(((cx, cy), 3))
                elif t is None and day <= 26:
                    if (cx, cy) in strawberry_slots and s_seeds > 0 and day <= 2:
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in melon_slots and m_seeds > 0 and (day <= 2 or 12 <= day <= 14):
                        needed.append(((cx, cy), 4))
                    elif (cx, cy) in carrot_slots and c_seeds > 0:
                        needed.append(((cx, cy), 4))

            if day >= 29 and has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            if needed:
                needed.sort(key=lambda item: (item[1], abs(wx - item[0][0]) + abs(wy - item[0][1])))
                tx, ty = needed[0][0]
                claimed_targets.add((tx, ty))
                return [_step_direction((wx, wy), (tx, ty))]
            elif has_items:
                tx, ty = shed_access
                return [_step_direction((wx, wy), (tx, ty))]

            return ["PASS"]

        farmer_act = resolve_worker_action(fx, fy, f_inv)

        hands_act = []
        for h_idx, (hx, hy) in enumerate(hands_pos):
            h_inv = inventories[h_idx + 1] if len(inventories) > h_idx + 1 else {}
            h_act = resolve_worker_action(hx, hy, h_inv)
            hands_act.append(h_act)

        return {"farmer": farmer_act, "hands": hands_act, "market": market_orders}

    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''

def build_and_verify_all():
    targets = [
        ("submission_v8_expanded_labor.py", V8_CODE),
        ("submission_v9_adaptive_quad.py", V9_CODE),
        ("submission_v10_apex_arbitrageur.py", V10_CODE),
    ]

    for fname, code in targets:
        p = Path(fname)
        p.write_text(code, encoding="utf-8")
        print(f"\n==================== {fname} ====================")
        
        # Test vs Starter
        env_s = ke.make("kaggriculture")
        env_s.run([str(p), "starter"])
        r_s = env_s.steps[-1][0]["reward"]
        stat_s = env_s.steps[-1][0]["status"]
        print(f"Vs Starter: Status={stat_s}, Reward=${r_s:,.2f}")

        # Test vs V4 as P0
        env_v4 = ke.make("kaggriculture")
        env_v4.run([str(p), "submission_v4_megacluster.py"])
        r_v4_sub = env_v4.steps[-1][0]["reward"]
        r_v4_opp = env_v4.steps[-1][1]["reward"]
        print(f"Vs V4 (Sub P0): Sub=${r_v4_sub:,.2f} vs V4=${r_v4_opp:,.2f} (Lead=${r_v4_sub - r_v4_opp:+,.2f})")

        # Test vs V4 as P1
        env_v4_2 = ke.make("kaggriculture")
        env_v4_2.run(["submission_v4_megacluster.py", str(p)])
        r_v4_opp2 = env_v4_2.steps[-1][0]["reward"]
        r_v4_sub2 = env_v4_2.steps[-1][1]["reward"]
        print(f"Vs V4 (Sub P1): Sub=${r_v4_sub2:,.2f} vs V4=${r_v4_opp2:,.2f} (Lead=${r_v4_sub2 - r_v4_opp2:+,.2f})")

if __name__ == "__main__":
    build_and_verify_all()
